version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: avideo_db
    hostname: avideo_db
    #tty: true
    ports:
      - 3306
    environment:
      - MYSQL_USER=avideo
      - MYSQL_PASSWORD=avideo
      - MYSQL_ROOT_PASSWORD=avideo
      - MYSQL_DATABASE=avideo
      - TZ=UTC
    expose:
      - 3306
    volumes:
      - ./storage/data:/var/lib/mysql
    networks:
      - app_net

  web:
    depends_on:
       - db
    hostname: avideo_web
    build: .
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
    expose:
      - 80
      - 443
    ports:
      - "80:80" 
    volumes:
      - .:/var/www/avideo:rw
    networks:
      - app_net

  encoder:
    depends_on:
       - db
    hostname: avideo_encoder
    build: ../AVideo-Encoder/
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/avideo:rw
    networks:
      - app_net

#Docker Networks
networks:
  app_net:
    driver: bridge

